# Generated by Django 5.2.8 on 2025-12-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_description_alter_car_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='state',
        ),
    ]
